In [1]:
#importing required libraries
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

In [2]:
#Reading the CSV file
data=pd.read_csv(r"C:/Users/Dell/Desktop/ML-MAJOR/ipl2017.csv")

In [3]:
#loading few values
data.head()

mid        date                  venue               bat_team  \
0    1  18-04-2008  M Chinnaswamy Stadium  Kolkata Knight Riders   
1    1  18-04-2008  M Chinnaswamy Stadium  Kolkata Knight Riders   
2    1  18-04-2008  M Chinnaswamy Stadium  Kolkata Knight Riders   
3    1  18-04-2008  M Chinnaswamy Stadium  Kolkata Knight Riders   
4    1  18-04-2008  M Chinnaswamy Stadium  Kolkata Knight Riders   

                     bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1   
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2   
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2   
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3   
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4   

   runs_last_5  wickets_last_5  striker  non-striker  total  
0            1               0        0            0    222  
1            1               0        0            0    222  
2            2               0        0            0    222  
3            2               0        0            0    222  
4            2               0        0            0    222

In [4]:
#check for 'n/a' in the entire dataset 
data.isnull().values.any()

False

In [5]:
#checking for null values and datatype in each column
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76014 entries, 0 to 76013
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   mid             76014 non-null  int64  
 1   date            76014 non-null  object 
 2   venue           76014 non-null  object 
 3   bat_team        76014 non-null  object 
 4   bowl_team       76014 non-null  object 
 5   batsman         76014 non-null  object 
 6   bowler          76014 non-null  object 
 7   runs            76014 non-null  int64  
 8   wickets         76014 non-null  int64  
 9   overs           76014 non-null  float64
 10  runs_last_5     76014 non-null  int64  
 11  wickets_last_5  76014 non-null  int64  
 12  striker         76014 non-null  int64  
 13  non-striker     76014 non-null  int64  
 14  total           76014 non-null  int64  
dtypes: float64(1), int64(8), object(6)
memory usage: 8.7+ MB


In [6]:
#Once again checking for missing values
data.isnull().sum()

mid               0
date              0
venue             0
bat_team          0
bowl_team         0
batsman           0
bowler            0
runs              0
wickets           0
overs             0
runs_last_5       0
wickets_last_5    0
striker           0
non-striker       0
total             0
dtype: int64

In [9]:
#having a better look at 'venue' column 
data['venue'].unique()

array(['M Chinnaswamy Stadium',
       'Punjab Cricket Association Stadium, Mohali', 'Feroz Shah Kotla',
       'Wankhede Stadium', 'Eden Gardens', 'Sawai Mansingh Stadium',
       'Rajiv Gandhi International Stadium, Uppal',
       'MA Chidambaram Stadium, Chepauk', 'Dr DY Patil Sports Academy',
       'Newlands', "St George's Park", 'Kingsmead', 'SuperSport Park',
       'Buffalo Park', 'New Wanderers Stadium', 'De Beers Diamond Oval',
       'OUTsurance Oval', 'Brabourne Stadium',
       'Sardar Patel Stadium, Motera', 'Barabati Stadium',
       'Vidarbha Cricket Association Stadium, Jamtha',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Holkar Cricket Stadium',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Subrata Roy Sahara Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'JSCA International Stadium Complex', 'Sheikh Zayed Stadium',
       'Sharjah Cricket Stadium', 'Dubai International Cricket St

In [10]:
#having a better look at 'bat_team' column 
data['bat_team'].unique()

array(['Kolkata Knight Riders', 'Chennai Super Kings', 'Rajasthan Royals',
       'Mumbai Indians', 'Deccan Chargers', 'Kings XI Punjab',
       'Royal Challengers Bangalore', 'Delhi Daredevils',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [11]:
#having a better look at 'bowl_team' column 
data['bowl_team'].unique()

array(['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Daredevils', 'Kolkata Knight Riders', 'Rajasthan Royals',
       'Mumbai Indians', 'Chennai Super Kings', 'Deccan Chargers',
       'Pune Warriors', 'Kochi Tuskers Kerala', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant'], dtype=object)

In [12]:
#having a better look at 'batsman' column 
data['batsman'].unique()

array(['SC Ganguly', 'BB McCullum', 'RT Ponting', 'DJ Hussey',
       'Mohammad Hafeez', 'PA Patel', 'ML Hayden', 'MEK Hussey',
       'MS Dhoni', 'SK Raina', 'JDP Oram', 'S Badrinath', 'T Kohli',
       'YK Pathan', 'SR Watson', 'M Kaif', 'DS Lehmann', 'RA Jadeja',
       'M Rawat', 'D Salunkhe', 'SK Warne', 'SK Trivedi', 'L Ronchi',
       'ST Jayasuriya', 'DJ Thornely', 'RV Uthappa', 'PR Shah',
       'AM Nayar', 'SM Pollock', 'Harbhajan Singh', 'AC Gilchrist',
       'Y Venugopal Rao', 'VVS Laxman', 'A Symonds', 'RG Sharma',
       'SB Styris', 'AS Yadav', 'SB Bangar', 'WPUJC Vaas', 'RP Singh',
       'K Goel', 'JR Hopes', 'KC Sangakkara', 'DPMD Jayawardene',
       'Yuvraj Singh', 'IK Pathan', 'S Sohal', 'B Lee', 'PP Chawla',
       'WA Mota', 'Shahid Afridi', 'RR Sarwan', 'S Sreesanth',
       'VRV Singh', 'S Chanderpaul', 'R Dravid', 'LRPL Taylor',
       'JH Kallis', 'V Kohli', 'MV Boucher', 'P Kumar', 'SB Joshi',
       'Z Khan', 'R Vinay Kumar', 'WP Saha', 'LR Shukla', 'AB Ag

In [13]:
#having a better look at 'bowler' column 
data['bowler'].unique()

array(['P Kumar', 'Z Khan', 'AA Noffke', 'JH Kallis', 'SB Joshi',
       'CL White', 'B Lee', 'S Sreesanth', 'JR Hopes', 'IK Pathan',
       'K Goel', 'PP Chawla', 'WA Mota', 'GD McGrath', 'B Geeves',
       'MF Maharoof', 'R Bhatia', 'DL Vettori', 'R Vinay Kumar',
       'B Akhil', 'AB Dinda', 'I Sharma', 'AB Agarkar', 'M Kartik',
       'Mohammad Hafeez', 'DJ Hussey', 'MM Patel', 'SR Watson',
       'SK Trivedi', 'SK Warne', 'D Salunkhe', 'Pankaj Singh',
       'YK Pathan', 'Mohammad Asif', 'VY Mahesh', 'SM Pollock', 'A Nehra',
       'DS Kulkarni', 'Harbhajan Singh', 'DJ Bravo', 'VS Yeligati',
       'AM Nayar', 'MA Khote', 'Sohail Tanvir', 'JDP Oram', 'MS Gony',
       'P Amarnath', 'M Muralitharan', 'Joginder Sharma', 'RP Singh',
       'DNT Zoysa', 'SB Bangar', 'Shahid Afridi', 'PP Ojha',
       'D Kalyankrishna', 'VRV Singh', 'Yuvraj Singh', 'DW Steyn',
       'CRD Fernando', 'ST Jayasuriya', 'V Kohli', 'Gagandeep Singh',
       'Umar Gul', 'SC Ganguly', 'LR Shukla', 'PJ Sangwan

In [14]:
#having a better look at 'runs' column 
data['runs'].unique()

array([  1,   2,   3,   7,  11,  17,  21,  22,  26,  27,  32,  38,  39,
        43,  44,  50,  54,  55,  59,  60,  61,  62,  63,  64,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  77,  78,  79,  80,  86,
        87,  88,  92,  98, 102, 108, 110, 111, 112, 116, 118, 119, 123,
       124, 125, 126, 127, 128, 130, 134, 135, 141, 145, 147, 148, 154,
       155, 157, 158, 159, 161, 162, 168, 170, 172, 173, 174, 178, 179,
       185, 191, 195, 196, 200, 206, 212, 214, 216, 222,   0,   5,   9,
        13,  19,  20,  25,  28,  29,  33,  34,  42,  46,  52,  53,  57,
        58,  76,  82,  83,  85,  94,  95,  97, 103, 107, 113, 117, 129,
       131, 132, 133, 136, 142, 143, 150, 151, 167, 169, 171, 177, 181,
       182, 183, 187, 188, 190, 204, 205, 207, 213, 215, 221, 227, 231,
       232, 238, 240,   8,  18,  31,  36,  37,  40,  41,  45,  47,  48,
        49,  51,  56,  65,  84,  93,  96, 100, 104, 106, 109, 120, 121,
         4,  23,  35,  81,  99, 101, 105, 114, 137, 138, 149, 15

In [15]:
#having a better look at 'wickets' column 
data['wickets'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64)

In [16]:
#having a better look at 'overs' column 
data['overs'].unique()

array([ 0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  1.1,  1.2,  1.3,  1.4,  1.5,
        1.6,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  3. ,  3.1,  3.2,  3.3,
        3.4,  3.5,  3.6,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  5.1,  5.2,
        5.3,  5.4,  5.5,  5.6,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  7.1,
        7.2,  7.3,  7.4,  7.5,  7.6,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        9.1,  9.2,  9.3,  9.4,  9.5,  9.6, 10.1, 10.2, 10.3, 10.4, 10.5,
       10.6, 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 12.1, 12.2, 12.3, 12.4,
       12.5, 12.6, 13.1, 13.2, 13.3, 13.4, 13.5, 13.6, 14.1, 14.2, 14.3,
       14.4, 14.5, 14.6, 15.1, 15.2, 15.3, 15.4, 15.5, 15.6, 16.1, 16.2,
       16.3, 16.4, 16.5, 16.6, 17.1, 17.2, 17.3, 17.4, 17.5, 17.6, 18.1,
       18.2, 18.3, 18.4, 18.5, 18.6, 19.1, 19.2, 19.3, 19.4, 19.5, 19.6,
       12. ,  4. ,  7. , 19. ,  9. ,  0. , 15. ,  5. , 16. ,  1. , 18. ,
        2. , 11. , 14. ,  6. , 13. ,  8. , 17. , 10. ])

In [17]:
#having a better look at 'runs_last_5' column 
data['runs_last_5'].unique()

array([  1,   2,   3,   7,  11,  17,  21,  22,  26,  27,  32,  38,  39,
        43,  44,  50,  54,  55,  59,  58,  52,  47,  45,  46,  41,  35,
        34,  30,  31,  24,  37,  40,  51,  61,  60,  62,  57,  56,  49,
        64,  67,  66,  71,  69,  68,   0,   5,   9,  13,  19,  20,  25,
        28,  29,  33,  42,  48,  53,  65,  63,  70,  72,  74,  79,  81,
        83,   8,  18,  36,  23,   4,  10,  12,  14,  15,  16,   6,  76,
        77,  80,  86,  75,  78,  85,  73,  88,  87,  93,  94,  89,  92,
        91,  82,  84,  95, 100, 104, 109, 110, 111, 113, 112], dtype=int64)

In [18]:
#having a better look at 'wickets_last_5' column 
data['wickets_last_5'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)

In [19]:
#having a better look at 'striker' column 
data['striker'].unique()

array([  0,   4,   8,  14,  18,  22,  23,  29,  35,  39,  40,  41,  42,
        43,  44,  45,  46,  47,  48,  50,  51,  57,  58,  59,  65,  67,
        68,  72,  74,  78,  79,  80,  81,  83,  89,  93,  99, 101, 102,
       103, 109, 111, 113, 114, 118, 119, 125, 131, 135, 136, 142, 148,
       150, 152, 158,   1,   5,   9,  13,  15,  10,  20,  21,  25,  16,
        17,  19,  26,  28,  30,  36,  37,  52,  53,  63,  64,  75,  76,
        82,  86,  87,  95, 100, 106, 108, 116,   6,   7,   3,  11,  12,
        24,  32,  33,  34,  38,  27,   2,  31,  49,  55,  56,  60,  66,
        61,  71,  69,  70,  77,  91,  92,  94, 107, 112, 117,  54,  62,
        73,  88,  90,  85,  84,  97, 104, 110, 115, 105,  98,  96, 121,
       127, 120, 128, 122, 126, 137, 143, 147, 153, 154, 155, 156, 160,
       161, 165, 166, 167, 173, 174, 175, 124, 132, 133, 129, 123],
      dtype=int64)

In [20]:
#having a better look at 'non-striker' column 
data['non-striker'].unique()

array([  0,   4,   5,   9,  10,   1,   3,   6,   7,   8,  13,  19,  20,
         2,  11,  12,  14,  15,  21,  25,  31,  32,  26,  30,  16,  17,
        18,  27,  35,  36,  37,  41,  47,  48,  50,  51,  53,  22,  24,
        29,  33,  23,  28,  42,  46,  34,  43,  49,  45,  39,  44,  52,
        38,  54,  55,  40,  56,  58,  59,  60,  61,  62,  66,  67,  68,
        72,  73,  74,  75,  76,  78,  79,  63,  57,  64,  65,  69,  71,
        81,  82,  70,  80,  87,  93,  95,  97, 103, 109], dtype=int64)

In [21]:
#having a better look at 'total' column 
data['total'].unique()

array([222, 240, 129, 165, 110, 166, 142, 208, 214, 182, 135, 147, 154,
       158, 178, 137, 191, 164, 196, 169, 162, 109, 126, 144, 103, 187,
       140, 122, 181, 204, 156, 143, 133, 221, 194,  67, 197, 189, 175,
       176, 211, 174, 145, 192, 112, 163, 101, 179, 184, 150, 168, 149,
       139, 119, 148, 141, 153, 105, 116, 157, 123, 173, 120, 160, 134,
       188, 170, 146, 161, 212, 190, 203, 218,  92, 185, 151, 171, 136,
       155, 183, 180, 177, 172, 246, 200, 159, 138, 111, 130, 132,  82,
        95,  81, 118, 195, 231,  94, 205, 125,  97, 232, 152, 198, 128,
       193, 115, 131, 124, 207, 100, 186, 114, 215,  99, 209, 117, 263,
        80, 223, 106,  70, 201, 226, 199, 127, 167, 235, 113, 202, 121,
        98, 227, 248, 206, 213, 230,  73, 107], dtype=int64)

In [22]:
#droping unnecessary columns 
data1=data.drop(['mid','date'],axis=1)

In [23]:
data1.head()

venue               bat_team                    bowl_team  \
0  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
1  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
2  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
3  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
4  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   

       batsman   bowler  runs  wickets  overs  runs_last_5  wickets_last_5  \
0   SC Ganguly  P Kumar     1        0    0.1            1               0   
1  BB McCullum  P Kumar     1        0    0.2            1               0   
2  BB McCullum  P Kumar     2        0    0.2            2               0   
3  BB McCullum  P Kumar     2        0    0.3            2               0   
4  BB McCullum  P Kumar     2        0    0.4            2               0   

   striker  non-striker  total  
0        0            0    222  
1        0            0    222  
2        0            0    222  
3        0            0    222  
4        0            0    222

In [24]:
#so far we have found the data to be very accurate and with abnormaties 
#we can proceed to hot encoding from here on. 

In [25]:
dummies1=pd.get_dummies(data1.venue)
dummies1.head()

Barabati Stadium  Brabourne Stadium  Buffalo Park  De Beers Diamond Oval  \
0                 0                  0             0                      0   
1                 0                  0             0                      0   
2                 0                  0             0                      0   
3                 0                  0             0                      0   
4                 0                  0             0                      0   

   Dr DY Patil Sports Academy  \
0                           0   
1                           0   
2                           0   
3                           0   
4                           0   

   Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium  \
0                                                  0     
1                                                  0     
2                                                  0     
3                                                  0     
4                                                  0     

   Dubai International Cricket Stadium  Eden Gardens  Feroz Shah Kotla  \
0                                    0             0                 0   
1                                    0             0                 0   
2                                    0             0                 0   
3                                    0             0                 0   
4                                    0             0                 0   

   Green Park  ...  Saurashtra Cricket Association Stadium  \
0           0  ...                                       0   
1           0  ...                                       0   
2           0  ...                                       0   
3           0  ...                                       0   
4           0  ...                                       0   

   Sawai Mansingh Stadium  Shaheed Veer Narayan Singh International Stadium  \
0                       0                                                 0   
1                       0                                                 0   
2                       0                                                 0   
3                       0                                                 0   
4                       0                                                 0   

   Sharjah Cricket Stadium  Sheikh Zayed Stadium  St George's Park  \
0                        0                     0                 0   
1                        0                     0                 0   
2                        0                     0                 0   
3                        0                     0                 0   
4                        0                     0                 0   

   Subrata Roy Sahara Stadium  SuperSport Park  \
0                           0                0   
1                           0                0   
2                           0                0   
3                           0                0   
4                           0                0   

   Vidarbha Cricket Association Stadium, Jamtha  Wankhede Stadium  
0                                             0                 0  
1                                             0                 0  
2                                             0                 0  
3                                             0                 0  
4                                             0                 0  

[5 rows x 35 columns]

In [26]:
data2=pd.concat([data1,dummies1],axis='columns')
data2.head()

venue               bat_team                    bowl_team  \
0  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
1  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
2  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
3  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   
4  M Chinnaswamy Stadium  Kolkata Knight Riders  Royal Challengers Bangalore   

       batsman   bowler  runs  wickets  overs  runs_last_5  wickets_last_5  \
0   SC Ganguly  P Kumar     1        0    0.1            1               0   
1  BB McCullum  P Kumar     1        0    0.2            1               0   
2  BB McCullum  P Kumar     2        0    0.2            2               0   
3  BB McCullum  P Kumar     2        0    0.3            2               0   
4  BB McCullum  P Kumar     2        0    0.4            2               0   

   ...  Saurashtra Cricket Association Stadium  Sawai Mansingh Stadium  \
0  ...                                       0                       0   
1  ...                                       0                       0   
2  ...                                       0                       0   
3  ...                                       0                       0   
4  ...                                       0                       0   

   Shaheed Veer Narayan Singh International Stadium  Sharjah Cricket Stadium  \
0                                                 0                        0   
1                                                 0                        0   
2                                                 0                        0   
3                                                 0                        0   
4                                                 0                        0   

   Sheikh Zayed Stadium  St George's Park  Subrata Roy Sahara Stadium  \
0                     0                 0                           0   
1                     0                 0                           0   
2                     0                 0                           0   
3                     0                 0                           0   
4                     0                 0                           0   

   SuperSport Park  Vidarbha Cricket Association Stadium, Jamtha  \
0                0                                             0   
1                0                                             0   
2                0                                             0   
3                0                                             0   
4                0                                             0   

   Wankhede Stadium  
0                 0  
1                 0  
2                 0  
3                 0  
4                 0  

[5 rows x 48 columns]

In [27]:
data2=data2.drop(['venue'],axis='columns')

In [28]:
dummies2=pd.get_dummies(data2.bat_team)
dummies2.head()
data3=pd.concat([data2,dummies2],axis='columns')
data3=data3.drop(['bat_team'],axis='columns')
data3.head()

bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1   
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2   
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2   
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3   
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4   

   runs_last_5  wickets_last_5  striker  non-striker  ...  Kings XI Punjab  \
0            1               0        0            0  ...                0   
1            1               0        0            0  ...                0   
2            2               0        0            0  ...                0   
3            2               0        0            0  ...                0   
4            2               0        0            0  ...                0   

   Kochi Tuskers Kerala  Kolkata Knight Riders  Mumbai Indians  Pune Warriors  \
0                     0                      1               0              0   
1                     0                      1               0              0   
2                     0                      1               0              0   
3                     0                      1               0              0   
4                     0                      1               0              0   

   Rajasthan Royals  Rising Pune Supergiant  Rising Pune Supergiants  \
0                 0                       0                        0   
1                 0                       0                        0   
2                 0                       0                        0   
3                 0                       0                        0   
4                 0                       0                        0   

   Royal Challengers Bangalore  Sunrisers Hyderabad  
0                            0                    0  
1                            0                    0  
2                            0                    0  
3                            0                    0  
4                            0                    0  

[5 rows x 60 columns]

In [29]:
dummies3=pd.get_dummies(data3.bowl_team)
data4=pd.concat([data3,dummies3],axis='columns')
data4=data4.drop(['bowl_team'],axis='columns')
data4.head()

batsman   bowler  runs  wickets  overs  runs_last_5  wickets_last_5  \
0   SC Ganguly  P Kumar     1        0    0.1            1               0   
1  BB McCullum  P Kumar     1        0    0.2            1               0   
2  BB McCullum  P Kumar     2        0    0.2            2               0   
3  BB McCullum  P Kumar     2        0    0.3            2               0   
4  BB McCullum  P Kumar     2        0    0.4            2               0   

   striker  non-striker  total  ...  Kings XI Punjab  Kochi Tuskers Kerala  \
0        0            0    222  ...                0                     0   
1        0            0    222  ...                0                     0   
2        0            0    222  ...                0                     0   
3        0            0    222  ...                0                     0   
4        0            0    222  ...                0                     0   

   Kolkata Knight Riders  Mumbai Indians  Pune Warriors  Rajasthan Royals  \
0                      0               0              0                 0   
1                      0               0              0                 0   
2                      0               0              0                 0   
3                      0               0              0                 0   
4                      0               0              0                 0   

   Rising Pune Supergiant  Rising Pune Supergiants  \
0                       0                        0   
1                       0                        0   
2                       0                        0   
3                       0                        0   
4                       0                        0   

   Royal Challengers Bangalore  Sunrisers Hyderabad  
0                            1                    0  
1                            1                    0  
2                            1                    0  
3                            1                    0  
4                            1                    0  

[5 rows x 73 columns]

In [30]:
dummies4=pd.get_dummies(data4.batsman)
data5=pd.concat([data4,dummies4],axis='columns')
data5=data5.drop(['batsman'],axis='columns')
data5.head()

bowler  runs  wickets  overs  runs_last_5  wickets_last_5  striker  \
0  P Kumar     1        0    0.1            1               0        0   
1  P Kumar     1        0    0.2            1               0        0   
2  P Kumar     2        0    0.2            2               0        0   
3  P Kumar     2        0    0.3            2               0        0   
4  P Kumar     2        0    0.4            2               0        0   

   non-striker  total  Barabati Stadium  ...  X Thalaivan Sargunam  Y Nagar  \
0            0    222                 0  ...                     0        0   
1            0    222                 0  ...                     0        0   
2            0    222                 0  ...                     0        0   
3            0    222                 0  ...                     0        0   
4            0    222                 0  ...                     0        0   

   Y Venugopal Rao  YA Abdulla  YK Pathan  YS Chahal  YV Takawale  \
0                0           0          0          0            0   
1                0           0          0          0            0   
2                0           0          0          0            0   
3                0           0          0          0            0   
4                0           0          0          0            0   

   Yashpal Singh  Yuvraj Singh  Z Khan  
0              0             0       0  
1              0             0       0  
2              0             0       0  
3              0             0       0  
4              0             0       0  

[5 rows x 483 columns]

In [31]:
dummies5=pd.get_dummies(data5.bowler)
data6=pd.concat([data5,dummies5],axis='columns')
data6=data6.drop(['bowler'],axis='columns')
data6.head()

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
0     1        0    0.1            1               0        0            0   
1     1        0    0.2            1               0        0            0   
2     2        0    0.2            2               0        0            0   
3     2        0    0.3            2               0        0            0   
4     2        0    0.4            2               0        0            0   

   total  Barabati Stadium  Brabourne Stadium  ...  WPUJC Vaas  \
0    222                 0                  0  ...           0   
1    222                 0                  0  ...           0   
2    222                 0                  0  ...           0   
3    222                 0                  0  ...           0   
4    222                 0                  0  ...           0   

   Washington Sundar  Y Gnaneswara Rao  Y Nagar  Y Venugopal Rao  YA Abdulla  \
0                  0                 0        0                0           0   
1                  0                 0        0                0           0   
2                  0                 0        0                0           0   
3                  0                 0        0                0           0   
4                  0                 0        0                0           0   

   YK Pathan  YS Chahal  Yuvraj Singh  Z Khan  
0          0          0             0       0  
1          0          0             0       0  
2          0          0             0       0  
3          0          0             0       0  
4          0          0             0       0  

[5 rows x 811 columns]

In [32]:
data6.shape

(76014, 811)

In [33]:
x=data6.drop('total',axis='columns')
x.head()

runs  wickets  overs  runs_last_5  wickets_last_5  striker  non-striker  \
0     1        0    0.1            1               0        0            0   
1     1        0    0.2            1               0        0            0   
2     2        0    0.2            2               0        0            0   
3     2        0    0.3            2               0        0            0   
4     2        0    0.4            2               0        0            0   

   Barabati Stadium  Brabourne Stadium  Buffalo Park  ...  WPUJC Vaas  \
0                 0                  0             0  ...           0   
1                 0                  0             0  ...           0   
2                 0                  0             0  ...           0   
3                 0                  0             0  ...           0   
4                 0                  0             0  ...           0   

   Washington Sundar  Y Gnaneswara Rao  Y Nagar  Y Venugopal Rao  YA Abdulla  \
0                  0                 0        0                0           0   
1                  0                 0        0                0           0   
2                  0                 0        0                0           0   
3                  0                 0        0                0           0   
4                  0                 0        0                0           0   

   YK Pathan  YS Chahal  Yuvraj Singh  Z Khan  
0          0          0             0       0  
1          0          0             0       0  
2          0          0             0       0  
3          0          0             0       0  
4          0          0             0       0  

[5 rows x 810 columns]

In [34]:
y=data6.total
y.head()

0    222
1    222
2    222
3    222
4    222
Name: total, dtype: int64

In [35]:
X_train, X_test, Y_train, Y_test= train_test_split(x,y, test_size=0.2, random_state=0)

In [36]:
model=RandomForestRegressor(n_estimators=100,random_state=0)

In [37]:
model.fit(X_train,Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

In [43]:
print(model.score(X_test,Y_test))

0.953275723105838
